package com.crud.alpha.clase.Localidad;

import com.crud.alpha.clase.Usuarios.Vendedor;
import jakarta.persistence.*;
import lombok.*;

//Modelado de la clase y tabla usuarios, @Tabla le da el nombre a la tabla, los demas @ nos ahorran declarar los getters
//Setters y constructor vacio y con argumentos.
// el @Id establece que atributo va a ser la clave primaria y el Identity hace que cada nuevo ID autogenerado sea el siguiente del anterior.

@Entity
@Table(name = "Localidad")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
public class Localidad {
// Importante no nombrar atributos utilizando '_' (piso/barra baja)

    // *** Autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    // *** Manual
    @Column(nullable = false)
    private String Nombre;


    // Fk tabla y relacion con Vendedor

    @ManyToOne
    @JoinColumn(name = "id_Vendedor", referencedColumnName = "id")  // id seria el atributo PK de Vendedor, idVendedor es el nombre que tendra en la BD este atributo.
    private Vendedor idVendedor;

}