package com.crud.alpha.clase.Localidad;

import com.crud.alpha.clase.Omnibus.Omnibus;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.time.LocalTime;

@Entity
@Table(name = "ultimaLocalidad")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class ultimaLocalidad {
// Importante no nombrar atributos utilizando '_' (piso/barra baja)

    // *** Autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // *** Manual
    @Column(nullable = false)
    private LocalDate fecha;

    @Column(nullable = false)
    private LocalTime hora;

    // *** FK
    @ManyToOne
    private Omnibus omnibus;

    @ManyToOne
    @JoinColumn(name = "localidad_nombre", referencedColumnName = "nombre")
    private Localidad localidad;

}