package com.crud.alpha.clase.Localidad;

import com.crud.alpha.clase.Omnibus.Omnibus;
import jakarta.persistence.*;
import lombok.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

@Entity
@EntityListeners(AuditingEntityListener.class)
@Table(name = "UltimaLocalidad")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class UltimaLocalidad {
// Importante no nombrar atributos utilizando '_' (piso/barra baja)

    // *** Autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // *** Manual
    @Column(nullable = true)
    private LocalDate fecha;

    @Column(nullable = true)
    private LocalTime hora;

    @CreatedDate
    private LocalDateTime createdAt;

    @LastModifiedDate
    private LocalDateTime updatedAt;

    // *** FK
    @ManyToOne
    @JoinColumn(name = "NroCoche", referencedColumnName = "nroCoche")
    private Omnibus omnibus;

    @ManyToOne
    @JoinColumn(name = "localidad_nombre", referencedColumnName = "id")
    private Localidad localidad;

}