package com.crud.alpha.clase.Localidad;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;

//Modelado de la clase y tabla usuarios, @Tabla le da el nombre a la tabla, los demas @ nos ahorran declarar los getters
//Setters y constructor vacio y con argumentos.
// el @Id establece que atributo va a ser la clave primaria y el Identity hace que cada nuevo ID autogenerado sea el siguiente del anterior.

@Entity
@Table(name = "ultimaLocalidad")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class ultimaLocalidad {
// Importante no nombrar atributos utilizando '_' (piso/barra baja)

    // *** Autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    // *** Manual

    @Column(nullable = false)
    private LocalDate fecha;

    @Column(nullable = false)
    private LocalDate hora;


    // *** FK

    @ManyToOne
    @JoinColumn(name = "ultima_localidad_id")
    private Localidad localidad_id;

}