package com.crud.alpha.clase.Omnibus;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.time.LocalTime;


//Modelado de la clase y tabla usuarios, @Tabla le da el nombre a la tabla, los demas @ nos ahorran declarar los getters
//Setters y constructor vacio y con argumentos.
// el @Id establece que atributo va a ser la clave primaria y el Identity hace que cada nuevo ID autogenerado sea el siguiente del anterior.

@Entity
@Table(name = "Mantenimiento")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Mantenimiento {
// Importante no nombrar atributos utilizando '_' (piso/barra baja)

    // *** Autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // *** Manual

    @Column(nullable = false)
    private LocalDate FechaDesde;

    @Column(nullable = false)
    private LocalTime HoraDesde;

    @Column(nullable = false)
    private LocalDate FechaHasta;

    @Column(nullable = false)
    private LocalTime HoraHasta;

    @Column(nullable = false)
    private String Motivo;

    // *** FK

    @ManyToOne
    @JoinColumn(name = "Omnibus_Id")
    private Omnibus OmnibusId;


}