package com.crud.alpha.clase.Omnibus;

import com.crud.alpha.clase.Pasaje.Pasaje;
import com.crud.alpha.enums.EstadoOmnibus;
import jakarta.persistence.*;
import lombok.*;

import java.util.List;


//Modelado de la clase y tabla usuarios, @Tabla le da el nombre a la tabla, los demas @ nos ahorran declarar los getters
//Setters y constructor vacio y con argumentos.
// el @Id establece que atributo va a ser la clave primaria y el Identity hace que cada nuevo ID autogenerado sea el siguiente del anterior.

@Entity
@Table(name = "Omnibus")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Omnibus {
// Importante no nombrar atributos utilizando '_' (piso/barra baja)

    // *** Autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // *** Manual

    @Column(nullable = false)
    private boolean activo;

    @Column(nullable = true)
    private int cantAsientos;

    @Column(nullable = true)
    private String descripcion;

    @Column(nullable = false)
    private int nroCoche;

    @Column(nullable = false)
    private EstadoOmnibus estado;

    @Column(nullable = false)
    private boolean accesibilidad;

    // *** FK

    @OneToMany(mappedBy = "id") // Opcional
    private List<Mantenimiento> Mantenimientos;

}