package com.crud.alpha.clase.Pasaje;

import com.crud.alpha.clase.Omnibus.Asiento;
import com.crud.alpha.clase.Viaje.Viaje;
import jakarta.persistence.*;
import lombok.*;


//Modelado de la clase y tabla usuarios, @Tabla le da el nombre a la tabla, los demas @ nos ahorran declarar los getters
//Setters y constructor vacio y con argumentos.
// el @Id establece que atributo va a ser la clave primaria y el Identity hace que cada nuevo ID autogenerado sea el siguiente del anterior.

@Entity
@Table(name = "Pasaje")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Pasaje {
// Importante no nombrar atributos utilizando '_' (piso/barra baja)

    // *** Autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    // *** Manual

    // *** FK Tabla y relacion con Asiento
    @ManyToOne
    @JoinColumn(name = "asiento", referencedColumnName = "id")
    private Asiento asiento;


    // *** FK Tabla y relacion con VentaPasaje
    @ManyToOne
    @JoinColumn(name = "id_compra_pasaje", referencedColumnName = "id")
    private VentaPasaje idCompraPasaje;


    // *** FK Tabla y relacion con Viaje
    @ManyToOne
    @JoinColumn(name = "idViaje", referencedColumnName = "id")  // id seria el atributo PK de Viaje, idViaje es el nombre que tendra en la BD este atributo.
    private Viaje idViaje;


}