package com.crud.alpha.clase.Pasaje;

import com.crud.alpha.clase.Omnibus.Asiento;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalTime;


//Modelado de la clase y tabla usuarios, @Tabla le da el nombre a la tabla, los demas @ nos ahorran declarar los getters
//Setters y constructor vacio y con argumentos.
// el @Id establece que atributo va a ser la clave primaria y el Identity hace que cada nuevo ID autogenerado sea el siguiente del anterior.

@Entity
@Table(name = "Pasaje")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Pasaje {
// Importante no nombrar atributos utilizando '_' (piso/barra baja)

    // *** Autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    // *** Manual

    @Column(nullable = false)
    private LocalTime hora_partida;

    @Column(nullable = false)
    private LocalTime hora_llegada;

    // *** FK

    @OneToOne(mappedBy = "pasaje")
    private Asiento asiento;


}