package com.crud.alpha.clase.Pasaje;

import com.crud.alpha.clase.Usuarios.Usuario;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.List;


//Modelado de la clase y tabla usuarios, @Tabla le da el nombre a la tabla, los demas @ nos ahorran declarar los getters
//Setters y constructor vacio y con argumentos.
// el @Id establece que atributo va a ser la clave primaria y el Identity hace que cada nuevo ID autogenerado sea el siguiente del anterior.

@Entity
@Table(name = "VentaPasaje")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class VentaPasaje {
// Importante no nombrar atributos utilizando '_' (piso/barra baja)

    // *** Autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // *** Manual
    @Column(nullable = false)
    private Long paymentId; // paymentId de mercadopago

    @Column(nullable = false)
    private LocalDateTime fechaCompra; // Aca le agregue LocalDateTime que nos da tanto hora como fecha para tener mas precision con el manejo.

    @Column(nullable = false)
    private String paymentStatus;

    // *** FK Cliente
    @ManyToOne
    @JoinColumn(nullable = false,name = "idCliente", referencedColumnName = "id")
    private Usuario idCliente;

    // *** Fk Pasaje
    @OneToMany(mappedBy = "idCompraPasaje")
    private List<Pasaje> idPasaje;

}




