package com.crud.alpha.clase.Usuarios;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
public class RegistroCliente {

    // *** Autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column
    private LocalDate fecha;

    // *** Manual

    @CreatedDate
    private LocalDateTime createdAt;

    @LastModifiedDate
    private LocalDateTime updatedAt;



    // fk Usuario

    @OneToOne
    @JoinColumn(name = "idUsuario", referencedColumnName = "id") // id seria el atributo PK de Usuario, idUsuario es el nombre que tendra en la BD este atributo.
    private Usuario idUsuario;

}